theme = "gruvbox"

[editor]
auto-format = false
cursorline = true
cursorcolumn = true
bufferline = "always"
color-modes = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
